### ISSUE TITLE
Exception in thread "main" joptsimple.UnrecognizedOptionException: J is not a recognized option

### ISSUE THREAD

**Issue by Robert-Rendell** [runelite/launcher#121]
Hello! I need some instructions to get RuneLite launcher running locally and some tips on how I can integrate my runelite client jar.
I've cloned the RuneLite launcher locally, but that's as far as I've been able to get.

I'm on `Ubuntu` and I'm running `com.adamcake.Bolt. My two accounts are both Jagex accounts, so running RuneLite on it's own is out of the question.

What I've tried so far:
- Using Bolt to load my custom runelite jar
- @Adam- has suggested modifying the runelite launcher to use my runelite client jar.

Here is the error when I try to run my runelite client jar with `com.adamcake.Bolt`:
```
rob@rob-XPS-15-9520:~$ export _JAVA_OPTIONS="-ea"
rob@rob-XPS-15-9520:~$ flatpak run com.adamcake.Bolt
[0108/001210.342559:ERROR:zygote_host_impl_linux.cc(218)] Failed to get Widevine CDM folder for sandbox forwarding
[0108/001210.570882:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Gtk-Message: 00:12:10.619: Failed to load module "canberra-gtk-module"
Gtk-Message: 00:12:10.621: Failed to load module "canberra-gtk-module"
[0108/001210.644357:WARNING:chrome_browser_cloud_management_controller.cc(87)] Could not create policy manager as CBCM is not enabled.
[B] OnContextInitialized
[B] Browser::Window popup constructor, this=94800378121728
[B] OnWindowCreated 0 this=94800378121728
[0108/001210.680034:WARNING:key_storage_linux.cc(183)] OSCrypt tried Libsecret but couldn't initialise.
[B] OnAfterCreated for browser 1
[B] OnBrowserCreated this=94800378121728 1
[R] OnBrowserCreated for browser 1
[R] OnLoadEnd for browser 1
[0108/001210.893334:ERROR:ev_root_ca_metadata.cc(161)] Failed to decode OID: 0
[B] runelite temp_dir: /run/user/1000/bolt-runelite-dobeTu
[B] Successfully spawned game process with pid 96
Picked up _JAVA_OPTIONS: -ea
Exception in thread "main" joptsimple.UnrecognizedOptionException: J is not a recognized option
	at joptsimple.OptionException.unrecognizedOption(OptionException.java:108)
	at joptsimple.OptionParser.validateOptionCharacters(OptionParser.java:633)
	at joptsimple.OptionParser.handleShortOptionCluster(OptionParser.java:528)
	at joptsimple.OptionParser.handleShortOptionToken(OptionParser.java:523)
	at joptsimple.OptionParserState$2.handleArgument(OptionParserState.java:59)
	at joptsimple.OptionParser.parse(OptionParser.java:396)
	at net.runelite.client.RuneLite.main(RuneLite.java:204)

```

Any assistance is greatly appreciated!

**Comment by Adam-** [comment]
This issue tracker is for issues with the RL launcher. This error is from you using a 3rd party launcher to launch your own client, which is not something which I support.
