### ISSUE TITLE
Launcher Stuck At 0%

### ISSUE THREAD

**Issue by Kspaeth93** [runelite/launcher#22]
Just started happening. I am on Windows 10 and I tried reinstalling the client, but no look. The problem looks to be this UnknownHostException. Anyone have a workaround or fix?

2018-06-07 20:23:27 [main] ERROR net.runelite.launcher.Launcher - error fetching bootstrap
java.net.UnknownHostException: static.runelite.net
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at net.runelite.launcher.Launcher.getBootstrap(Launcher.java:250)
	at net.runelite.launcher.Launcher.main(Launcher.java:136)

**Comment by Kspaeth93** [comment]
Error with my network configuration, sorry. No issue here.
