### ISSUE TITLE
Unable to resolve dependencies for client

### ISSUE THREAD

**Issue by Andrek25** [runelite/launcher#54]
Launcher doesn't open.
`[main] ERROR net.runelite.launcher.Launcher - unable to resolve dependencies for client
org.eclipse.aether.resolution.DependencyResolutionException: Could not transfer artifact net.runelite:client:jar:1.5.13.1 from/to central (http://mvn.runelite.net/): Forbidden (403)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:355)
	at net.runelite.launcher.ArtifactResolver.resolveArtifacts(ArtifactResolver.java:86)
	at net.runelite.launcher.Launcher.main(Launcher.java:179)
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact net.runelite:client:jar:1.5.13.1 from/to central (http://mvn.runelite.net/): Forbidden (403)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:422)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:224)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:338)
	... 2 common frames omitted
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact net.runelite:client:jar:1.5.13.1 from/to central (http://mvn.runelite.net/): Forbidden (403)
	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:52)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:365)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:75)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:583)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:259)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:498)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:399)
	... 4 common frames omitted
Caused by: org.apache.http.client.HttpResponseException: Forbidden (403)
	at org.eclipse.aether.transport.http.HttpTransporter.handleStatus(HttpTransporter.java:475)
	at org.eclipse.aether.transport.http.HttpTransporter.execute(HttpTransporter.java:300)
	at org.eclipse.aether.transport.http.HttpTransporter.implGet(HttpTransporter.java:252)
	at org.eclipse.aether.spi.connector.transport.AbstractTransporter.get(AbstractTransporter.java:67)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:453)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:360)
	... 9 common frames omitted`

**Comment by deathbeam** [comment]
Update your launcher, you are on outdated version
