### ISSUE TITLE
RuneLite launcher sudden close on 0%

### ISSUE THREAD

**Issue by Silenor** [runelite/launcher#55]
Runelite launcher used to be run at normal for years but I can't open it today, anyone could help?

2019-02-23 00:31:37 [main] INFO  net.runelite.launcher.Launcher - Setting hardware acceleration to DIRECTDRAW
2019-02-23 00:31:37 [main] ERROR net.runelite.launcher.Launcher - error fetching bootstrap
java.security.SignatureException: Signature length not correct: got 2784 but was expecting 512
	at sun.security.rsa.RSASignature.engineVerify(RSASignature.java:189)
	at java.security.Signature$Delegate.engineVerify(Signature.java:1222)
	at java.security.Signature.verify(Signature.java:655)
	at net.runelite.launcher.Launcher.getBootstrap(Launcher.java:275)
	at net.runelite.launcher.Launcher.main(Launcher.java:168)

**Comment by Alexsuperfly** [comment]
https://github.com/runelite/runelite/wiki/Troubleshooting-problems-with-the-client
