### ISSUE TITLE
Runelite won't load :error loading client! Check logs for details

### ISSUE THREAD

**Issue by ozofpowder** [runelite/launcher#63]
My runelite and osrs on main website wont load. I have uninstalled and reinstalled runelite and java but still nothing. this is my log

Last login: Thu Jun  6 09:45:55 on ttys000
SAMUELs-MacBook-Pro:~ iSammy$ /Users/iSammy/Desktop/RuneLite.app/Contents/MacOS/RuneLite ; exit;
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
10:12:37,508 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
10:12:37,508 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
10:12:37,508 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/Users/iSammy/Desktop/RuneLite.app/Contents/Resources/RuneLite.jar!/logback.xml]
10:12:37,530 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@13b6d03 - URL [jar:file:/Users/iSammy/Desktop/RuneLite.app/Contents/Resources/RuneLite.jar!/logback.xml] is not of type file
10:12:37,635 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
10:12:37,651 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
10:12:37,654 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
10:12:37,664 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
10:12:37,751 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
10:12:37,756 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE]
10:12:37,785 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@257895351 - No compression will be used
10:12:37,786 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@257895351 - Will use the pattern /Users/iSammy/.runelite/logs/launcher_%d{yyyy-MM-dd}.%i.log for the active file
10:12:37,789 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@73035e27 - The date pattern is 'yyyy-MM-dd' from file name pattern '/Users/iSammy/.runelite/logs/launcher_%d{yyyy-MM-dd}.%i.log'.
10:12:37,789 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@73035e27 - Roll-over at midnight.
10:12:37,794 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@73035e27 - Setting initial period to Thu Jun 06 10:09:39 BST 2019
10:12:37,794 |-WARN in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@73035e27 - SizeAndTimeBasedFNATP is deprecated. Use SizeAndTimeBasedRollingPolicy instead
10:12:37,794 |-WARN in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@73035e27 - For more information see http://logback.qos.ch/manual/appenders.html#SizeAndTimeBasedRollingPolicy
10:12:37,798 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
10:12:37,800 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - Active log file name: /Users/iSammy/.runelite/logs/launcher.log
10:12:37,800 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - File property is set to [/Users/iSammy/.runelite/logs/launcher.log]
10:12:37,801 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
10:12:37,801 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
10:12:37,801 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE] to Logger[ROOT]
10:12:37,801 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
10:12:37,802 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@64c64813 - Registering current configuration as safe fallback point

2019-06-06 10:12:37 [main] INFO  net.runelite.launcher.Launcher - Setting hardware acceleration to OPENGL
2019-06-06 10:12:39 [main] INFO  net.runelite.launcher.Launcher - Verified hash of client-1.5.25.jar
2019-06-06 10:12:39 [main] INFO  net.runelite.launcher.Launcher - Verified hash of slf4j-api-1.7.25.jar
2019-06-06 10:12:39 [main] INFO  net.runelite.launcher.Launcher - Verified hash of logback-classic-1.2.3.jar
2019-06-06 10:12:39 [main] INFO  net.runelite.launcher.Launcher - Verified hash of logback-core-1.2.3.jar
2019-06-06 10:12:39 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jopt-simple-5.0.1.jar
2019-06-06 10:12:39 [main] INFO  net.runelite.launcher.Launcher - Verified hash of guava-23.2-jre.jar
2019-06-06 10:12:39 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jsr305-1.3.9.jar
2019-06-06 10:12:39 [main] INFO  net.runelite.launcher.Launcher - Verified hash of error_prone_annotations-2.0.18.jar
2019-06-06 10:12:39 [main] INFO  net.runelite.launcher.Launcher - Verified hash of j2objc-annotations-1.1.jar
2019-06-06 10:12:39 [main] INFO  net.runelite.launcher.Launcher - Verified hash of animal-sniffer-annotations-1.14.jar
2019-06-06 10:12:39 [main] INFO  net.runelite.launcher.Launcher - Verified hash of guice-4.1.0-no_aop.jar
2019-06-06 10:12:39 [main] INFO  net.runelite.launcher.Launcher - Verified hash of javax.inject-1.jar
2019-06-06 10:12:39 [main] INFO  net.runelite.launcher.Launcher - Verified hash of aopalliance-1.0.jar
2019-06-06 10:12:39 [main] INFO  net.runelite.launcher.Launcher - Verified hash of gson-2.8.5.jar
2019-06-06 10:12:39 [main] INFO  net.runelite.launcher.Launcher - Verified hash of substance-8.0.02.jar
2019-06-06 10:12:39 [main] INFO  net.runelite.launcher.Launcher - Verified hash of trident-1.5.00.jar
2019-06-06 10:12:39 [main] INFO  net.runelite.launcher.Launcher - Verified hash of commons-text-1.2.jar
2019-06-06 10:12:39 [main] INFO  net.runelite.launcher.Launcher - Verified hash of commons-lang3-3.7.jar
2019-06-06 10:12:39 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jogl-all-2.3.2.jar
2019-06-06 10:12:39 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jogl-all-2.3.2-natives-windows-amd64.jar
2019-06-06 10:12:39 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jogl-all-2.3.2-natives-windows-i586.jar
2019-06-06 10:12:39 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jogl-all-2.3.2-natives-linux-amd64.jar
2019-06-06 10:12:39 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jogl-all-2.3.2-natives-linux-i586.jar
2019-06-06 10:12:39 [main] INFO  net.runelite.launcher.Launcher - Verified hash of gluegen-rt-2.3.2.jar
2019-06-06 10:12:39 [main] INFO  net.runelite.launcher.Launcher - Verified hash of gluegen-rt-2.3.2-natives-windows-amd64.jar
2019-06-06 10:12:39 [main] INFO  net.runelite.launcher.Launcher - Verified hash of gluegen-rt-2.3.2-natives-windows-i586.jar
2019-06-06 10:12:39 [main] INFO  net.runelite.launcher.Launcher - Verified hash of gluegen-rt-2.3.2-natives-linux-amd64.jar
2019-06-06 10:12:39 [main] INFO  net.runelite.launcher.Launcher - Verified hash of gluegen-rt-2.3.2-natives-linux-i586.jar
2019-06-06 10:12:39 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jbsdiff-1.0.jar
2019-06-06 10:12:39 [main] INFO  net.runelite.launcher.Launcher - Verified hash of commons-compress-1.5.jar
2019-06-06 10:12:39 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jna-4.5.1.jar
2019-06-06 10:12:39 [main] INFO  net.runelite.launcher.Launcher - Verified hash of jna-platform-4.5.1.jar
2019-06-06 10:12:39 [main] INFO  net.runelite.launcher.Launcher - Verified hash of runelite-api-1.5.25.jar
2019-06-06 10:12:39 [main] INFO  net.runelite.launcher.Launcher - Verified hash of client-patch-1.5.25.jar
2019-06-06 10:12:39 [main] INFO  net.runelite.launcher.Launcher - Verified hash of http-api-1.5.25.jar
2019-06-06 10:12:39 [main] INFO  net.runelite.launcher.Launcher - Verified hash of okhttp-3.7.0.jar
2019-06-06 10:12:39 [main] INFO  net.runelite.launcher.Launcher - Verified hash of okio-1.12.0.jar
2019-06-06 10:12:39 [main] INFO  net.runelite.launcher.Launcher - Verified hash of commons-csv-1.4.jar
2019-06-06 10:12:40 [main] INFO  net.runelite.launcher.Launcher - Verified hash of discord-1.1.jar
10:12:40,074 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
10:12:40,074 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
10:12:40,074 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/Users/iSammy/.runelite/repository2/client-1.5.25.jar!/logback.xml]
10:12:40,082 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@573beede - URL [jar:file:/Users/iSammy/.runelite/repository2/client-1.5.25.jar!/logback.xml] is not of type file
10:12:40,128 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
10:12:40,134 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
10:12:40,137 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
10:12:40,141 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
10:12:40,155 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
10:12:40,157 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE]
10:12:40,167 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@861993279 - No compression will be used
10:12:40,168 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@861993279 - Will use the pattern /Users/iSammy/.runelite/logs/client_%d{yyyy-MM-dd}.%i.log for the active file
10:12:40,171 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@7be06070 - The date pattern is 'yyyy-MM-dd' from file name pattern '/Users/iSammy/.runelite/logs/client_%d{yyyy-MM-dd}.%i.log'.
10:12:40,171 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@7be06070 - Roll-over at midnight.
10:12:40,171 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@7be06070 - Setting initial period to Thu Jun 06 10:09:42 BST 2019
10:12:40,172 |-WARN in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@7be06070 - SizeAndTimeBasedFNATP is deprecated. Use SizeAndTimeBasedRollingPolicy instead
10:12:40,172 |-WARN in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@7be06070 - For more information see http://logback.qos.ch/manual/appenders.html#SizeAndTimeBasedRollingPolicy
10:12:40,174 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
10:12:40,176 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - Active log file name: /Users/iSammy/.runelite/logs/client.log
10:12:40,176 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - File property is set to [/Users/iSammy/.runelite/logs/client.log]
10:12:40,176 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
10:12:40,176 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
10:12:40,177 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE] to Logger[ROOT]
10:12:40,177 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
10:12:40,177 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@20fe0e0d - Registering current configuration as safe fallback point

2019-06-06 10:12:40 [RuneLite] ERROR net.runelite.client.rs.ClientLoader - Error loading RS!
java.net.ProtocolException: Unexpected status line: ldschool.runescape.comPHTTP/1.1 302 MOVED
	at okhttp3.internal.http.StatusLine.parse(StatusLine.java:69)
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:75)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at net.runelite.http.api.RuneLiteAPI$1.intercept(RuneLiteAPI.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
	at okhttp3.RealCall.execute(RealCall.java:69)
	at net.runelite.client.rs.ClientConfigLoader.fetch(ClientConfigLoader.java:59)
	at net.runelite.client.rs.ClientLoader.load(ClientLoader.java:88)
	at net.runelite.client.RuneLiteModule.provideApplet(RuneLiteModule.java:103)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.inject.internal.ProviderMethod$ReflectionProviderMethod.doProvision(ProviderMethod.java:292)
	at com.google.inject.internal.ProviderMethod$Factory.provision(ProviderMethod.java:401)
	at com.google.inject.internal.ProviderMethod$Factory.get(ProviderMethod.java:376)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:54)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:132)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:120)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1054)
	at net.runelite.client.RuneLite.main(RuneLite.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.runelite.launcher.ReflectionLauncher$1.run(ReflectionLauncher.java:78)
2019-06-06 10:12:40 [RuneLite] INFO  n.r.client.account.SessionManager - No session file exists
2019-06-06 10:12:41 [RuneLite] WARN  n.r.client.ClientSessionManager - error opening session
javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
	at sun.security.ssl.InputRecord.handleUnknownRecord(InputRecord.java:710)
	at sun.security.ssl.InputRecord.read(InputRecord.java:527)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:268)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:238)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:149)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:192)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
	at okhttp3.RealCall.execute(RealCall.java:69)
	at net.runelite.client.SessionClient.open(SessionClient.java:49)
	at net.runelite.client.ClientSessionManager.start(ClientSessionManager.java:57)
	at net.runelite.client.RuneLite.start(RuneLite.java:258)
	at net.runelite.client.RuneLite.main(RuneLite.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.runelite.launcher.ReflectionLauncher$1.run(ReflectionLauncher.java:78)
2019-06-06 10:12:41 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,0,23,1280x728,layout=java.awt.BorderLayout,title=RuneLite,resizable,maximized,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,809x534,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@3838e174,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2019-06-06 10:12:41 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2019-06-06 10:12:42 [pool-3-thread-1] WARN  n.r.client.plugins.feed.FeedPlugin - null
javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
	at sun.security.ssl.InputRecord.handleUnknownRecord(InputRecord.java:710)
	at sun.security.ssl.InputRecord.read(InputRecord.java:527)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:268)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:238)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:149)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:192)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
	at okhttp3.RealCall.execute(RealCall.java:69)
	at net.runelite.http.api.feed.FeedClient.lookupFeed(FeedClient.java:54)
	at net.runelite.client.plugins.feed.FeedPlugin.lambda$new$0(FeedPlugin.java:75)
	at com.google.common.base.Suppliers$ExpiringMemoizingSupplier.get(Suppliers.java:235)
	at net.runelite.client.plugins.feed.FeedPanel.rebuildFeed(FeedPanel.java:121)
	at net.runelite.client.plugins.feed.FeedPlugin.updateFeed(FeedPlugin.java:110)
	at net.runelite.client.util.RunnableExceptionLogger.run(RunnableExceptionLogger.java:41)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-06-06 10:12:42 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 2614ms. Uptime: 5683ms
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by Nightfirecat** [comment]
1. This is [a client issue](https://github.com/runelite/runelite), not a launcher issue.
2. From the following line, it seems your connection is trying redirect you while RuneLite is fetching the vanilla OSRS client. I would advise [following the Troubleshooting guide on our client wiki page](https://github.com/runelite/runelite/wiki/Troubleshooting-problems-with-the-client#client-not-launching) and trying to access it over a VPN.

  ```
  2019-06-06 10:12:40 [RuneLite] ERROR net.runelite.client.rs.ClientLoader - Error loading RS!
java.net.ProtocolException: Unexpected status line: ldschool.runescape.comPHTTP/1.1 302 MOVED
  ```
